### ISSUE TITLE
Move I/O libraries

### ISSUE THREAD

**Issue by waywardmonkeys** [project-mindy/mindy#37]
Since we don't have the backward compatibility concerns, should we make the jump from having separate libraries for `standard-io`, `format`, `print`, and `format-out` and merge them into a single `io` library and update everything to use reflect that.

That'll bring us closer to Open Dylan compatibility as well.

**Comment by waywardmonkeys** [comment]
@dram What do you think?

**Comment by dram** [comment]
I like this idea. As IO is commonly needed, merging them into a single library will speed up Mindy startup time a bit.

Also compatibility with Open Dylan is really important, so that resources can be shared, e.g. docs, test suites.
